### ISSUE TITLE
Dataset split in YAGO

### ISSUE THREAD

**Issue by JuliaGast** [JuliaGast/TGB2#20]
needs to be modified for the automated downloaded dataset

`dataset.py`

```
        if ("yago" in self.name):

            _train_mask, _val_mask, _test_mask = self.generate_splits(full_data, val_ratio=0.1, test_ratio=0.10) 
```

**Comment by JuliaGast** [comment]
The problem is that I changed the dataset split for yago in dataset.py
-> when the dataset is downloaded, the train/valid/test set is downloaded/split with the new split
however, the negative samples are still downloaded with the old split; one needs to manually delete the negative sample pkl files and run tkgl_yago_ns_gen.py

Can we automatically provide the correct new split for these negative samples?

**Comment by JuliaGast** [comment]
Note: this might no longer be needed as soon as we implement the new method for time-aware filtered mrr computation without negative samples.

**Comment by shenyangHuang** [comment]
issue resolved
