### ISSUE TITLE
Add Timetraveler

### ISSUE THREAD

**Issue by GastJulia** [JuliaGast/TGB2#26]
[Timetraveler](https://github.com/JHL-HUST/TITer/tree/master)

ongoing

Tasks:

- [x] restructure code s.t. it fits tgb
- [x] implement data loading and make sure it is in correct format for Timetraveler
- [x] add preprocessing
- [x] add dirichlet distribution step
- [x] check if the relation ids still make sense
- [x] integrate test()
- [x] store and load models at correct location
- [x] compute scores for negative samples only
- [x] compute and log mrr
- [x] compute and log runtime

**Comment by JuliaGast** [comment]
done
