### ISSUE TITLE
Bug in Neg Sampler for THG

### ISSUE THREAD

**Issue by JuliaGast** [JuliaGast/TGB2#28]
I think it should be
`
neg_d_arr = filtered_dst[(pos_t, pos_s, e_type)] in l. 123 of thg_negative_sampler.py`

instead of
`neg_d_arr = filtered_dst`

right?

with current implementation I get
for this:
![image](https://github.com/JuliaGast/TGB2/assets/41183430/44b3858a-4b07-4a16-86ef-fab63e41f119)
the following:
![image](https://github.com/JuliaGast/TGB2/assets/41183430/272186bc-6c20-4d7a-9ce5-1836a49ed19f)

where:

![image](https://github.com/JuliaGast/TGB2/assets/41183430/f3e74e85-6589-46a8-a4dd-2f1e303495e3)

**Comment by shenyangHuang** [comment]
fixed in the recent PR

**Comment by JuliaGast** [comment]
fixed
