### ISSUE TITLE
Integrate Recurrency Baseline 

### ISSUE THREAD

**Issue by JuliaGast** [JuliaGast/TGB2#3]
- [x] for polecat
- [x] for mini-yago

**Comment by shenyangHuang** [comment]
let's discuss tomorrow but starting with MRR ranking over all possible destination could be a good starting point to get an idea of what kind of performance we have on the dataset. We don't want datasets where methods already has overly high performance to begin with

**Comment by JuliaGast** [comment]
todos: 

- [ ] find out why the performance is significantly slower than when I run my original code (for yago)
- [ ] check if the mrr scores are similar for yago. careful: slightly different test timesteps (5 instead of 6 test timesteps)

**Comment by JuliaGast** [comment]
YAGO:
without training:
```
   {
        "model": "RecurrencyBaseline",
        "train_flag": false,
        "data": "tkgl-yago",
        "run": 1,
        "seed": 1,
        "mrr": 0.8588335514068604,
        "hits10": 0.9259546399116516,
        "test_time": 175.950186,
        "tot_train_val_time": 190.072089
    }
```

with training:
```
   {
        "mrr": 0.9088966846466064,
        "hits10": 0.930065929889679,
        runtimes: TODO log
   }
```
