### ISSUE TITLE
Can we have dataset.num_nodes and dataset.num_rels

### ISSUE THREAD

**Issue by JuliaGast** [JuliaGast/TGB2#6]
It would be great to have these two properties for each dataset.

- [ ] `num_nodes`: number of distinct node ids in train+valid+test set
- [ ] `num_rels`: number of distinct edge_types in train+valid+test set

Otherwise I have to compute it for every method (also fine)

`num_rels = len(set(dataset.edge_type))`

`num_nodes = len(set(dataset.full_data['sources']+ dataset.full_data['destinations']))`

**Comment by shenyangHuang** [comment]
Yes, this can be supported in the next iteration.

**Comment by shenyangHuang** [comment]
issue addressed in #8

**Comment by JuliaGast** [comment]
great thanks. closing this.
