### ISSUE TITLE
Code for time-aware filtered MRR computation

### ISSUE THREAD

**Issue by JuliaGast** [JuliaGast/TGB2#7]
- [x] time-aware filtered mrr computation: integrate
- [x] do we also log hits@1, 3, 10? I think this would be useful.

**Comment by shenyangHuang** [comment]
For the benchmark, we should only track one metric per dataset. Of course for our development process, we can look at different metric and see what makes sense the most. I think MRR would be the most strict metric as if you evaluate with many (potentially all negatives), the model has to rank the positive edge as top 1. While hits@10, it just needs to be top 10.

**Comment by shenyangHuang** [comment]
knowledge graph on OGB is computed with MRR:
https://ogb.stanford.edu/docs/linkprop/

**Comment by shenyangHuang** [comment]
This is solved in pull request #12
